18812 MainProcess 2023-10-28 13:11:35,888
Traceback (most recent call last):
  File "D:\conda\env\ai\Lib\site-packages\pyarmor\cli\__main__.py", line 712, in main
    main_entry(sys.argv[1:])
  File "D:\conda\env\ai\Lib\site-packages\pyarmor\cli\__main__.py", line 700, in main_entry
    return args.func(ctx, args)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\conda\env\ai\Lib\site-packages\pyarmor\cli\__main__.py", line 230, in cmd_gen
    builder.process(options)
  File "D:\conda\env\ai\Lib\site-packages\pyarmor\cli\generate.py", line 158, in process
    self._obfuscate_scripts()
  File "D:\conda\env\ai\Lib\site-packages\pyarmor\cli\generate.py", line 120, in _obfuscate_scripts
    code = Pytransform3.generate_obfuscated_script(self.ctx, r) #here lies licence check
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\conda\env\ai\Lib\site-packages\pyarmor\cli\core\__init__.py", line 104, in generate_obfuscated_script
    return m.generate_obfuscated_script(ctx, res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<maker>", line 666, in generate_obfuscated_script
  File "D:\conda\env\ai\Lib\site-packages\pyarmor\cli\__init__.py", line 16, in process
    return meth(self, res, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<maker>", line 505, in process
  File "<maker>", line 511, in coserialize
  File "<maker>", line 556, in _build_ast_body
RuntimeError: out of license
